#This Python file uses the following encoding: utf-8
'''
Post process the tam results by taking only nouns in Topic and only adjectives, verbs and adverbs in Aspects.
Takes a tam output file.
Run it as tam_post_processing.py tam_output_file
where tam_output_file is an output generated by tam on any of the datasets
Author: Hemed Kaporo.
'''

import codecs, sys, os, nltk
reload(sys)
sys.setdefaultencoding('utf8')

#Get the command line arguments
inputfile = sys.argv[1]
outputfile = inputfile +'_post'

nouns_tags = ['NN','NNS','NNP','NNPS']
opinion_tags = ['JJ','JJR','JJS','RB','RBR','RBS','RP','VB','VBD','VBG','VBN','VBZ']
t=False # t stands for isTopic
p=False # c stands for isPerspective

with codecs.open(inputfile, encoding='utf-8', mode='r') as inputFile:
     for line in inputFile:
         line = line.strip()
         if not line: continue
         if line[0:5] == 'Topic' and t==False:
            t=True
            p=False
            with codecs.open(outputfile,encoding='utf-8',mode='a') as outputFile: 
                 outputFile.write('--%s\n' %(line))
         else:
            POS_tagged = nltk.tag.pos_tag([line])
            if p==True:                             
               if POS_tagged[0][1] in opinion_tags or line[0:6] == 'Aspect':
                  with codecs.open(outputfile,encoding='utf-8',mode='a') as outputFile: 
                       outputFile.write('%s\n' %(line))
               else: continue
            else:
               if POS_tagged[0][1] in nouns_tags and line[0:6] != 'Aspect':
                  with codecs.open(outputfile,encoding='utf-8',mode='a') as outputFile: 
                       outputFile.write('%s\n' %(line))
               else: 
                  if line[0:6] == 'Aspect':
                     t=False
                     p=True
                     with codecs.open(outputfile,encoding='utf-8',mode='a') as outputFile: 
                          outputFile.write('--%s\n' %(line))
                  else: continue

